spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-streams
    streams:
      properties:
        default:
          deserialization:
            exception:
              handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler


kafka:
  topics:
    input-topic1: task1-1
    output-topic1: task1-2
    input-topic2: task2
    input-topic3-1: task3-1
    input-topic3-2: task3-2
    input-topic4: task4